// keynames.go — platform-specific name→ebiten.Key table.
//
// This is the only place in the codebase that knows what string
// "ArrowUp" means in terms of ebiten.Key. Keeping it here means the pure
// core internal/input package can remain backend-agnostic: a future SDL
// or web backend would ship its own parseKey with the same string
// vocabulary.
//
// Coverage
//
//   - Alphabet A-Z  (matches ebiten.KeyA .. ebiten.KeyZ)
//   - Digits  Digit0-Digit9  (main row) and KP_0..KP_9 (numpad)
//   - Arrows  ArrowUp/Down/Left/Right
//   - Editing Enter, Escape, Space, Tab, Backspace, Delete, Insert, Home,
//     End, PageUp, PageDown
//   - Modifiers Shift / Control / Alt (plus Left/Right variants)
//   - Function F1..F12
//   - Punctuation Bracket* Minus Equal Semicolon Quote Backslash Slash
//     Comma Period Grave
//
// Anything else in the JSON file produces a warning at bind time and is
// silently ignored (the action ends up with fewer / zero bound keys).
// That is the right failure mode: we don't want a typo in keybinds.json
// to prevent the game from launching.
package ebitenplat

import "github.com/hajimehoshi/ebiten/v2"

// keyByName resolves a config-file key name to its Ebiten key value.
// ok is false for unknown names.
func keyByName(name string) (ebiten.Key, bool) {
	k, ok := keyNames[name]
	return k, ok
}

// keyNames maps the symbolic names used in keybinds.json to the
// corresponding ebiten.Key. Generated by hand; keep alphabetical within
// each group for greppability.
var keyNames = map[string]ebiten.Key{
	// Alphabet.
	"A": ebiten.KeyA, "B": ebiten.KeyB, "C": ebiten.KeyC, "D": ebiten.KeyD,
	"E": ebiten.KeyE, "F": ebiten.KeyF, "G": ebiten.KeyG, "H": ebiten.KeyH,
	"I": ebiten.KeyI, "J": ebiten.KeyJ, "K": ebiten.KeyK, "L": ebiten.KeyL,
	"M": ebiten.KeyM, "N": ebiten.KeyN, "O": ebiten.KeyO, "P": ebiten.KeyP,
	"Q": ebiten.KeyQ, "R": ebiten.KeyR, "S": ebiten.KeyS, "T": ebiten.KeyT,
	"U": ebiten.KeyU, "V": ebiten.KeyV, "W": ebiten.KeyW, "X": ebiten.KeyX,
	"Y": ebiten.KeyY, "Z": ebiten.KeyZ,

	// Digit row.
	"Digit0": ebiten.KeyDigit0, "Digit1": ebiten.KeyDigit1,
	"Digit2": ebiten.KeyDigit2, "Digit3": ebiten.KeyDigit3,
	"Digit4": ebiten.KeyDigit4, "Digit5": ebiten.KeyDigit5,
	"Digit6": ebiten.KeyDigit6, "Digit7": ebiten.KeyDigit7,
	"Digit8": ebiten.KeyDigit8, "Digit9": ebiten.KeyDigit9,

	// Numpad digits.
	"KP_0": ebiten.KeyNumpad0, "KP_1": ebiten.KeyNumpad1,
	"KP_2": ebiten.KeyNumpad2, "KP_3": ebiten.KeyNumpad3,
	"KP_4": ebiten.KeyNumpad4, "KP_5": ebiten.KeyNumpad5,
	"KP_6": ebiten.KeyNumpad6, "KP_7": ebiten.KeyNumpad7,
	"KP_8": ebiten.KeyNumpad8, "KP_9": ebiten.KeyNumpad9,

	// Arrows.
	"ArrowUp":    ebiten.KeyArrowUp,
	"ArrowDown":  ebiten.KeyArrowDown,
	"ArrowLeft":  ebiten.KeyArrowLeft,
	"ArrowRight": ebiten.KeyArrowRight,

	// Editing cluster.
	"Enter":     ebiten.KeyEnter,
	"Escape":    ebiten.KeyEscape,
	"Space":     ebiten.KeySpace,
	"Tab":       ebiten.KeyTab,
	"Backspace": ebiten.KeyBackspace,
	"Delete":    ebiten.KeyDelete,
	"Insert":    ebiten.KeyInsert,
	"Home":      ebiten.KeyHome,
	"End":       ebiten.KeyEnd,
	"PageUp":    ebiten.KeyPageUp,
	"PageDown":  ebiten.KeyPageDown,

	// Modifiers. The bare names act as "either side"; Left/Right variants
	// let users pin a specific physical key.
	"Shift":        ebiten.KeyShift,
	"ShiftLeft":    ebiten.KeyShiftLeft,
	"ShiftRight":   ebiten.KeyShiftRight,
	"Control":      ebiten.KeyControl,
	"ControlLeft":  ebiten.KeyControlLeft,
	"ControlRight": ebiten.KeyControlRight,
	"Alt":          ebiten.KeyAlt,
	"AltLeft":      ebiten.KeyAltLeft,
	"AltRight":     ebiten.KeyAltRight,
	"Meta":         ebiten.KeyMeta, // Command on macOS, Windows key on Windows.
	"MetaLeft":     ebiten.KeyMetaLeft,
	"MetaRight":    ebiten.KeyMetaRight,

	// Function row.
	"F1": ebiten.KeyF1, "F2": ebiten.KeyF2, "F3": ebiten.KeyF3,
	"F4": ebiten.KeyF4, "F5": ebiten.KeyF5, "F6": ebiten.KeyF6,
	"F7": ebiten.KeyF7, "F8": ebiten.KeyF8, "F9": ebiten.KeyF9,
	"F10": ebiten.KeyF10, "F11": ebiten.KeyF11, "F12": ebiten.KeyF12,

	// Punctuation / symbols (US layout names; ebiten uses physical-key
	// semantics so the printed character depends on layout).
	"BracketLeft":  ebiten.KeyBracketLeft,
	"BracketRight": ebiten.KeyBracketRight,
	"Minus":        ebiten.KeyMinus,
	"Equal":        ebiten.KeyEqual,
	"Semicolon":    ebiten.KeySemicolon,
	"Quote":        ebiten.KeyQuote,
	"Backslash":    ebiten.KeyBackslash,
	"Slash":        ebiten.KeySlash,
	"Comma":        ebiten.KeyComma,
	"Period":       ebiten.KeyPeriod,
	"Backquote":    ebiten.KeyBackquote,
}
