package editorweb

import (
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// Map identity and the world grid.
//
// A map id is the .tmj path under the maps root, without the extension:
// "F-5", "field1", "rooms/boss". Ids reach this package straight off an HTTP
// path, so everything here is also a security boundary — see safeSegment.

// GridCols and GridRows describe the overworld grid generated by
// cmd/genworldgrid: cells A-1 through J-10.
const (
	GridCols = 10
	GridRows = 10
)

var (
	// ErrBadMapID covers every rejection reason on purpose: a caller poking at
	// path traversal should not learn which check caught them.
	ErrBadMapID = errors.New("invalid map id")

	// safeSegment is the actual traversal defense. path.Clean alone is not
	// enough — it happily yields ".." for "../../etc/passwd" — so each segment
	// must independently match an allowlist.
	safeSegment = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._\-]*$`)

	// gridIDPattern matches cell ids like "F-5" and "J-10".
	gridIDPattern = regexp.MustCompile(`^([A-Za-z])-([0-9]{1,2})$`)
)

// maxMapIDDepth allows "rooms/boss" but nothing deeper; assets/maps has exactly
// one level of subdirectory.
const maxMapIDDepth = 2

// NormalizeMapID validates an id from an untrusted source and returns its
// canonical slash-separated form. A trailing ".tmj" is accepted and stripped so
// links can carry either spelling.
func NormalizeMapID(id string) (string, error) {
	id = strings.TrimSuffix(id, ".tmj")
	if id == "" || len(id) > 200 || strings.ContainsAny(id, "\x00\\") {
		return "", ErrBadMapID
	}
	// Validate the RAW segments. Do not path.Clean first: Clean *absorbs* ".."
	// rather than rejecting it, silently rewriting "../../etc/passwd" into
	// "etc/passwd" and serving a different map than was asked for. Splitting the
	// raw string means "..", "" (from a leading or doubled slash) and a trailing
	// slash all fail the allowlist, because none of them start alphanumeric.
	segs := strings.Split(id, "/")
	if len(segs) > maxMapIDDepth {
		return "", ErrBadMapID
	}
	for _, seg := range segs {
		if !safeSegment.MatchString(seg) {
			return "", ErrBadMapID
		}
	}
	return id, nil
}

// GridPos is a cell's position in the overworld grid.
type GridPos struct {
	Col    int    `json:"col"`    // 0-based, 1..10, west to east
	Row    int    `json:"row"`    // 0-based, A..J, north to south
	Letter string `json:"letter"` // "A".."J"
	Number int    `json:"number"` // 1..10
}

// ParseGridID decodes a grid cell id.
//
// The letter is the ROW (y, north to south: A..J) and the number is the COLUMN
// (x, west to east: 1..10), matching internal/scenes/map.go.
func ParseGridID(id string) (GridPos, bool) {
	m := gridIDPattern.FindStringSubmatch(id)
	if m == nil {
		return GridPos{}, false
	}
	letter := strings.ToUpper(m[1])
	row := int(letter[0] - 'A')
	number, err := strconv.Atoi(m[2])
	if err != nil {
		return GridPos{}, false
	}
	col := number - 1
	if col < 0 || col >= GridCols || row < 0 || row >= GridRows {
		return GridPos{}, false
	}
	return GridPos{Col: col, Row: row, Letter: letter, Number: number}, true
}

// FormatGridID is the inverse of ParseGridID.
func FormatGridID(col, row int) (string, bool) {
	if col < 0 || col >= GridCols || row < 0 || row >= GridRows {
		return "", false
	}
	return fmt.Sprintf("%c-%d", 'A'+row, col+1), true
}

// MapGroup buckets maps for the browser sidebar.
type MapGroup string

const (
	GroupGrid       MapGroup = "grid"
	GroupRoom       MapGroup = "room"
	GroupStandalone MapGroup = "standalone"
)

// GroupOf classifies a map id for the sidebar.
func GroupOf(id string) MapGroup {
	if _, ok := ParseGridID(id); ok {
		return GroupGrid
	}
	if strings.HasPrefix(id, "rooms/") {
		return GroupRoom
	}
	return GroupStandalone
}
